
* Overview
This is modification of Smart Dashboard from WPILib. This repository is a work in progress for FIRST team 348 in the 2011 season, however the intent is to add any useful feature back to the official dashboard. As a result, certain widgets or features (such as all my modifications to fakerobot) I add may be far too specific to be added back to the actual Smart Dashboard.

* Fake Robot
The fake robot sends random data to the dashboard. It is designed to be within what is reasonable for what is pretending to be, but it is rather jittery as a result.

If you'd like to customize it to your robot, modify main.java in client/fakerobot/src/.... Although, unless you're using a feature I've added and that hasn't been added to the official repository, I'd recommend checking it out from: http://firstforge.wpi.edu/sf/projects/smartdashboard

* Smart Dashboard
The normal Smart Dashboard with added some widgets:

** FormattedLabel
A label that can be added from the view menu to display whatever text you desire.

** BooleanPic
A widget that toggles between two pictures based off of the value of the boolean. Ideally improving the usability of the dashboard by allowing easy visual recognition.

** VerticalProgressBar
A vertical progress bar that allows you to change it's size, scale and color.

** TimeField
A field that displays time and that may change the color of the text to alert that a certain amount of time is left. (i.e. turn red at 15 seconds)

* Features to add [0/9]
** TODO Digital display widget for speed
** TODO Support for files in the properties dialog
** TODO Support to change the background color
** TODO Have VerticalProgressBar automagically handle scaling
** TODO Support for checkboxes in the properties dialog
** TODO Merge VerticalProgressBar into ProgressBar
** TODO Ask to save before quiting
** TODO Add support for multiple saves
** TODO Bold text
